Vagrant.configure("2") do |config|

hostnames = ['Debian12-']
servers = []
subnet=100


hostnames.each { |node_name|
  (1..2).each {|n|
    nodenum = "#{n}".rjust(2,'0')
    subnet += 1
    servers << {:hostname => "#{node_name}#{nodenum}",  :ip => "192.168.41.#{subnet}", :box => 'generic-x64/debian12'} 
  }
}

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
     # node.vm.disk :disk, size: machine[:disk_size], primary: true
      node.vm.hostname = machine[:hostname]
      node.vm.network "public_network", bridge: "Default Switch"
      node.vm.provider "hyperv" do |vb|
        vb.vmname = machine[:hostname]
        vb.memory = 2048
        vb.cpus = 2
        vb.auto_start_action = "Nothing"
        vb.auto_stop_action = "ShutDown"
    
    config.vm.provision "shell",
      name: "postgresql", path: "pgsql-setup/pgsql-init.sh", privileged: true

      end
     end
  end
end
